/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PodcastRouteImport } from './routes/podcast'
import { Route as MerchRouteImport } from './routes/merch'
import { Route as EpisodiosRouteImport } from './routes/episodios'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as IndexRouteImport } from './routes/index'

const PodcastRoute = PodcastRouteImport.update({
  id: '/podcast',
  path: '/podcast',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchRoute = MerchRouteImport.update({
  id: '/merch',
  path: '/merch',
  getParentRoute: () => rootRouteImport,
} as any)
const EpisodiosRoute = EpisodiosRouteImport.update({
  id: '/episodios',
  path: '/episodios',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/episodios': typeof EpisodiosRoute
  '/merch': typeof MerchRoute
  '/podcast': typeof PodcastRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/episodios': typeof EpisodiosRoute
  '/merch': typeof MerchRoute
  '/podcast': typeof PodcastRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/episodios': typeof EpisodiosRoute
  '/merch': typeof MerchRoute
  '/podcast': typeof PodcastRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/contacto' | '/episodios' | '/merch' | '/podcast'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/contacto' | '/episodios' | '/merch' | '/podcast'
  id: '__root__' | '/' | '/contacto' | '/episodios' | '/merch' | '/podcast'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactoRoute: typeof ContactoRoute
  EpisodiosRoute: typeof EpisodiosRoute
  MerchRoute: typeof MerchRoute
  PodcastRoute: typeof PodcastRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/podcast': {
      id: '/podcast'
      path: '/podcast'
      fullPath: '/podcast'
      preLoaderRoute: typeof PodcastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merch': {
      id: '/merch'
      path: '/merch'
      fullPath: '/merch'
      preLoaderRoute: typeof MerchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/episodios': {
      id: '/episodios'
      path: '/episodios'
      fullPath: '/episodios'
      preLoaderRoute: typeof EpisodiosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactoRoute: ContactoRoute,
  EpisodiosRoute: EpisodiosRoute,
  MerchRoute: MerchRoute,
  PodcastRoute: PodcastRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
